### ISSUE TITLE
Name pull requests to group them by the stack their in

### ISSUE THREAD

**Issue by jessep** [ezyang/ghstack#10]
I'm evaluating this library and just made a test repo, pushed some stacked diffs on master, then created a feature branch, pushed that stack. The problem I saw right away is that as a code reviewer, I can't look at my PRs tab and understand what's going on, the PRs simply have the names of the commits. I'd expect them to be prepended by some information to groups them in the way you already do with the branch names and whatnot. 

![](https://cl.ly/8ecd3d27365d/Image%202019-10-07%20at%2012.56.39%20PM.png)

I'm assuming y'all have a way of working around this, maybe you don't use the "Pull requests" tab on github? Would appreciate understanding how you approach this.

**Comment by ezyang** [comment]
Yeah, we don't use the PR tab :) (instead, we use the internal navigation on the PRs to find our way around the diff.) You could manually simulate this by adding the information by hand to each diff.

(BTW, if you're evaluating this, note that https://github.com/ezyang/ghstack/issues/9 will need to be resolved before you can actually usefully use this tool. It's not a hard bit of functionality, but in our use case we don't actually need it so it's bitrotten a little.)
