### ISSUE TITLE
Unpin `importlib_metadata` requirement?

### ISSUE THREAD

**Issue by pmeier** [ezyang/ghstack#124]
It is currently pinned to 

https://github.com/ezyang/ghstack/blob/7bc9d40c43cf31e7af4ad7032262db1201f98cd6/pyproject.toml#L22

`importlib_metadata >=3, <4`. Is there a reason for pinning this?

If not, can we unpin or at least expand the range? `sphinx==5.0.0`, which is used by [PyTorch](https://github.com/pytorch/pytorch/blob/ce856cee7eeea9a6eb5ed30fa512b38b3d8f3edf/docs/requirements.txt#L1), needs at least [`importlib_metadata>=4.4`](https://github.com/sphinx-doc/sphinx/blob/953002e6261bdd9314ee0a3314aae19479a88c7e/setup.py#L30).

Somewhat related, can we maybe also specify this only as requirement for Python < 3.8 similar to what we do for `dataclasses`?

https://github.com/ezyang/ghstack/blob/7bc9d40c43cf31e7af4ad7032262db1201f98cd6/pyproject.toml#L21

IIUC, the package is only used in

https://github.com/ezyang/ghstack/blob/a5d20a469c75cdd5c77a90e362a3d89921d46229/ghstack/__init__.py#L3-L5

which can be replaced with something like

```py
import sys

if sys.version_info >= (3, 8):
    import importlib.metadata as importlib_metadata
else:
    import importlib_metadata

__version__ = importlib_metadata.version("ghstack")
```

**Comment by ezyang** [comment]
Sure. Send a PR?
