### ISSUE TITLE
ghstack land can land a stack you didn't specify if they share branches

### ISSUE THREAD

**Issue by poteto** [ezyang/ghstack#133]
I came across this issue today when I accidentally re-ran a previous `ghstack land` command in my terminal history.

When I re-ran `ghstack land https://github.com/redacted/redacted/pull/940` (a stack that had I had already merged into main), my work in progress stack was landed instead. Both these stacks happened to share the same temporary gh branches and I think this must have resulted in the accidental merge.

Ideally if you run `ghstack land` with a PR that's already been merged it should throw an error. Let me know if you want me to provide a repro.

Thanks!

**Comment by ezyang** [comment]
Blegh, ok I see why this happened (it's because we delete branches so branch numbers can be reused.) The proposed fix sounds good if you can implement it, ow you'll have to wait till I'm over covid lol
