### ISSUE TITLE
Beginner question: how to get ghstack alias?

### ISSUE THREAD

**Issue by mlanln** [ezyang/ghstack#151]
Beginner question, apologies if issues is the wrong forum to ask.

The installation instructions say to install ghstack with pip3:

```
pip3 install ghstack
```

Afterwards, `ghstack` is used as an alias. But this doesn't work on my system:

```
% ghstack
zsh: command not found: ghstack
```

How do I get this alias defined?

**Comment by amyreese** [comment]
On zsh, you may need to run 'rehash' first.

**Comment by ezyang** [comment]
The other common explanation is your pip install directory is not in PATH

**Comment by mlanln** [comment]
> The other common explanation is your pip install directory is not in PATH



That was my issue, thanks!
