### ISSUE TITLE
ci: tests fail on `windows-latest` with Python `3.11`

### ISSUE THREAD

**Issue by felix-seifert** [ezyang/ghstack#172]
The change which introduced testing on Windows [succeeded in all tests](https://github.com/ezyang/ghstack/actions/runs/6941349372/job/18906334398). However, executing the tests with the same code base on the master branch resulted in [a failure](https://github.com/ezyang/ghstack/actions/runs/6953207301/job/18917997700) for the combination `windows-latest` and Python version `3.12`.

Observing the diff between the [commit of the succeeding tests](https://github.com/ezyang/ghstack/commit/4e6f1fc) and the failing tests shows that [there is no difference](https://github.com/ezyang/ghstack/compare/master..4e6f1fc).

The failure occurs during the dependency installation. Similar to some [dependencies not being ready for Python 3.12](https://github.com/ezyang/ghstack/pull/168), we could also just say that some dependencies are not ready for Windows and Python 3.11. However, a green test showed that the dependencies seem to be okay.

We can either accept the issue and exclude running CI on Windows and 3.11, or we update some dependency versions.

**Comment by ezyang** [comment]
If you can update the deps that would be great, o/w I'll just revert
