### ISSUE TITLE
Merge to master from GitHub UI or with other checks passing?

### ISSUE THREAD

**Issue by AnthonyMillerSF** [ezyang/ghstack#18]
We have Jenkins and CodeCov jobs that are running on our PRs. In the GitHub UI, this blocks merging into master until all of those pass. It's unclear how/if we could use `ghstack` and maintain all those other checks and making PRs for in the GitHub UI. Does this work?

**Comment by ezyang** [comment]
You want to prevent merging to master before all checks pass. ghstack PRs cannot be directly landed from UI, they have to be landed with `ghstack land`. It would be a simple matter to update this command to block landing unless GitHub statuses were all green. PRs accepted!

**Comment by AnthonyMillerSF** [comment]
Ahh I see. Okay thanks! I'm a bit crunched right now, wish I had more time for open source contribution. If you guys don't get around to it, maybe eventually I'll find the time.
Thanks for building and releasing this. Really cool tool.
