### ISSUE TITLE
Failures in GH Action jobs are not obvious

### ISSUE THREAD

**Issue by felix-seifert** [ezyang/ghstack#201]
As already experienced in #176, test failures do not let the GH Actions job fail. [This job on Windows](https://github.com/ezyang/ghstack/actions/runs/7073285925/job/19253009262), for example, shows test failures in the `Run tests` step. However, the job is still green. To discover these test failures, you would have to scan every job for each workflow run.

DoD: Failures of the test suite should make a GH Actions job fail/be red.

**Comment by ezyang** [comment]
The problem was you were suppressing the exit code of the child processes. I went ahead and fixed it.
