### ISSUE TITLE
ghstack 0.9.0 not working for private repos

### ISSUE THREAD

**Issue by alangpierce** [ezyang/ghstack#234]
Hi, thanks for the great project! We use it quite a bit at Benchling.

In 0.8.0 and earlier, when following the instructions to generate an access token, we've been including the full `repo` scope (not just `public_repo` recommended in the prompt), which makes it possible to use ghstack against our private monorepo. That has worked great, but unfortunately, with the release of 0.9.0 it looks like the `public_repo` scope is now [hard-coded](https://github.com/ezyang/ghstack/blob/8f9608a71a25146311706b3e8aaf30ca197e6159/ghstack/config.py#L103), so we get an error about the repo not being found. Would it be possible to support private repos by changing the scope to `repo`, maybe behind an option?

**Comment by ezyang** [comment]
Yup. I guess I don't mind if we unconditionally ask for private access too. Send us a PR

**Comment by amartani** [comment]
@ezyang I was able to successfully use `ghstack` at HEAD on our private repo; would you be able to trigger a new release for the package so that we can roll it out internally? Thank you!

**Comment by ezyang** [comment]
> @ezyang I was able to successfully use `ghstack` at HEAD on our private repo; would you be able to trigger a new release for the package so that we can roll it out internally? Thank you!

done!
