### ISSUE TITLE
Base branch commit has no parent commits set

### ISSUE THREAD

**Issue by amartani** [ezyang/ghstack#238]
While testing out the new version of ghstack, I noticed that the base commits seem to not have a parent commit set. This causes PR branches to be considered completely distinct, breaking, for example, `git merge-base`, which we use in our CI to determine the set of files changed in a PR.

I created an example ghstack PR, with the current HEAD version, here: https://github.com/amartani/ghstack/pull/4

The base commit of that PR is https://github.com/amartani/ghstack/commit/178ded52f779747a57fd034a7fad6fa9ed7cb793

As you can see in the GitHub UI, this commit has "0 parents", and shows the entire repo as a "diff".

In contrast, previous versions of ghstack would set the parent of the base commit properly, such that the base commit would generally show as a no-diff commit.

**Comment by ezyang** [comment]
If you git merge-base the head and the base branch, it won't matter that the base commit doesn't have a parent set because the base is guaranteed to be reachable from head branch.

I could randomly assign a parent commit pointer but in many situations it's not meaningful

**Comment by amartani** [comment]
I'm not sure if I completely follow the comment, but to make my point clearer:

```
git remote add amartani git@github.com:amartani/ghstack.git
git fetch amartani
git merge-base amartani/gh/amartani/4/head amartani/master
git merge-base amartani/gh/amartani/4/base amartani/master
```

Both `git merge-base` commands fail - they can't find any merge-base with the base branch. On previous versions, the base commit parent would point to a commit in `master` (similar to what happens on a manually-created PR branch). This allows, for example, for CI to properly list all files changed, considering the entire stack.

**Comment by ezyang** [comment]
Yes. But it's incorrect to unconditionally compute merge-base with amartani/master. You should be doing

git merge-base amartani/gh/amartani/4/head amartani/gh/amartani/4/base

You can see that this is incorrect because if someone makes a PR to a non-master branch, you would still diff against master, according to what you did here!
