### ISSUE TITLE
README instructions on modifying PRs is unclear

### ISSUE THREAD

**Issue by aftix** [ezyang/ghstack#259]
The README says to "just edit the commit in question", but that does not work for me. If I run `ghstack submit --direct` then `git rebase -i main` to edit the commit, then `ghstack --direct`, ghstack produces a new stack instead of updating the old one. I must first run `ghstack checkout <PR url>` after submitting a stack, then I can update the stack instead of creating new ones. The documentation should be updated to be clearer on which commit exactly to modify here (i.e. modify the commit in the gh/user/num/orig branch, not the branch you submitted).

**Comment by ezyang** [comment]
So, specifically, once you ghstack submit a commit, ghstack edits the commit message with metadata associating it with the PR. While you can make edits to the commits (e.g., file contents), you can't remove the commit message metadata or we will make a new PR stack.

If you are running `ghstack submit` and your HEAD is not getting moved to the edited commit, that's a bug and you should tell us about it.

**Comment by aftix** [comment]
I've been unable to reproduce this issue, I guess I must have removed the metadata at some point.
