### ISSUE TITLE
Configurable `.ghstackrc` location?

### ISSUE THREAD

**Issue by xiaohan-xue** [ezyang/ghstack#260]
Hello! 

How would people feel about allowing the location of `.ghstackrc` to be optionally read from an environment variable? We're using ghstack inside docker containers, where a mounted volume holds various config files to persist them across container rebuilds, and it would be nice if we could specify a config file location for ghstack so we could plop it into the volume instead of having to bind mount the `~/.ghstackrc` location.

Would be more than happy to open a PR changing https://github.com/ezyang/ghstack/blob/a53b4fe0fbbf121e4ff2ddd1410c76927efd22bc/ghstack/config.py#L44 if it's just that straightforward!

Thanks for making this awesome tool :3

**Comment by ezyang** [comment]
sure, send a patch

**Comment by xiaohan-xue** [comment]
thanks!! put up https://github.com/ezyang/ghstack/pull/261

**Comment by xiaohan-xue** [comment]
hi again~ would really appreciate if anyone with permissions could run `poetry publish --build` so that 0.9.4 is pullable/this can be closed, whenever is convenient

tysm

**Comment by xiaohan-xue** [comment]
saw that this is now available, thanks so much!!
