### ISSUE TITLE
fatal: Not a valid object name HEAD:.github/ghstack_direct

### ISSUE THREAD

**Issue by yanbing-j** [ezyang/ghstack#265]
I find in ghstack 0.9.4 has the fatal error, while 0.9.3 can work well.

$ ghstack
$ git remote get-url ssh
$ git cat-file -e HEAD:.github/ghstack_direct
fatal: Not a valid object name HEAD:.github/ghstack_direct

**Comment by ezyang** [comment]
Actually, are you sure this is actually a problem? IIUC, it will print this but it will keep going right?

**Comment by yanbing-j** [comment]
Oh, yes. It will not block the procedure even with 0.9.4 version. Thanks for the remind!

**Comment by ezyang** [comment]
thanks
