### ISSUE TITLE
Modifying existing PRs 

### ISSUE THREAD

**Issue by giovannizotta** [ezyang/ghstack#268]
I just started using `ghstack`. 

I have 2 PRs, one stacked on top of each other:
- PR1 (base)
- PR2 (on top of PR1)

If I need to modify PR1, what is the expected process?

I imagined:
* checkout PR1, make changes, `git commit --amend`
* run `ghstack` (probably a mistake)
* checkout PR2, rebase on PR1
* run `ghstack`

However, this did not work as expected, and I am a bit confused by the many branches that have been created and I am not sure how to solve this situation. Some guidance on how this usually works is really appreciated!

**Comment by ezyang** [comment]
In vanilla git, I recommend using `git rebase -i`. So `git rebase -i $(git merge-base origin/main HEAD)`, 'edit' the commit you want, git rebase --continue, ghstack.

If you want to checkout PR1, and then you want to update PR2, you have to cherry-pick PR2 on top of your amended PR1. And it has to be the orig comimt; if you lost it you should use origin/gh/giovannizotta/XX/orig as the cherry-pick.

**Comment by giovannizotta** [comment]
Thank you for the quick reply @ezyang! 

I'm a bit confused by the process. If I had to do this manually via vanilla git, I would:
1. checkout PR1, make changes and `git commit --amend`
2. checkout PR2, rebase on top of PR1
3. repeat rebase for any PR on top of PR2

How does this process look like with `ghstack`? If I have to cherry-pick PR2 on top of PR1 any time I make a change and fiddle with open PRs it sounds like more work than the vanilla git solution. Am I missing something?

**Comment by giovannizotta** [comment]
Now I understand what you meant by `git rebase -i`. I was missing the fact that you have to checkout the top-most PR in the stack, instead checking out the commit you want to edit. And from the interactive rebase, just edit the commit. Makes sense!
