### ISSUE TITLE
Landing all (appended) commits in PRs

### ISSUE THREAD

**Issue by yang** [ezyang/ghstack#48]
If a reviewer appends commits to PRs (say, via the Github UI), is there a way to have `ghstack land` (and `ghstack checkout`) to not drop these? Thanks!

**Comment by ezyang** [comment]
It wouldn't be hard to add a sanity check for `ghstack land` to detect if this situation occurred and bailed out. A little more difficult is to actually incorporate these back into the orig commit, but it also seems doable; just take the tree from head and zonk it back into orig. Need a little coding to do it.

**Comment by yang** [comment]
Yeah, I wasn't familiar enough with the overarching design to understand why it merges /orig rather than /head, but it sounds like it's possible to just merge /head instead? (Would potentially need to stop along the way to resolve any conflicts introduced with later PRs).

**Comment by ezyang** [comment]
It merges orig because it's easier to do, no other good reason :)

**Comment by yang** [comment]
Out of curiosity, what's the reason for amending the commit messages to indicate 'poisoned'? I was initially hoping for a solution like the following in land.py, but it would merge the poisoned commit messages.

```
-sh.git("cherry-pick", remote_name + "/" + orig_ref)
+sh.git("cherry-pick", remote_name + "/" + base_ref, remote_name + "/" + head_ref)
```

**Comment by ezyang** [comment]
It's because sometimes people checkout the head branch, and then try to run ghstack (which is super bad, it'll create a new PR per amend, without poisoning)

**Comment by ezyang** [comment]
Duping this as https://github.com/ezyang/ghstack/issues/169
