### ISSUE TITLE
Make commit messages more descriptive

### ISSUE THREAD

**Issue by samestep** [ezyang/ghstack#61]
Currently `ghstack` is wont to produce long strings of fairly unhelpful identical commit messages, usually just "Update on <name of PR>". Example:

- https://github.com/pytorch/pytorch/pull/54924/commits

Since the goal is for these sorts of PRs to eventually be squashed and merged into a single commit on the default branch, it would be nice (if possible) for `ghstack` to give more descriptive commit messages for these updates, such as "rebased onto commit x".

**Comment by ezyang** [comment]
I would like to fix this but I am not sure what exactly the desired alternate default message here is.

The particular example @samestep gave is that he'd like to know if we'd rebased on master. We can identify that a rebase has occurred and change the message to say that a rebase had happened. If you wanted to be extra fancy, you could try to work out if it was a clean rebase or not.

But the rest of your messages will still be the unhelpful default. I suppose we could do something like list the files that were changed, or ask ChatGPT to summarize the change. But overall I'm not really sure how much better we can make the default.

**Comment by samestep** [comment]
It's been a while since I thought about this, but perhaps one approach could be to just do what Git itself does, letting the user manually specify a commit message?

**Comment by ezyang** [comment]
You can, just say `ghstack -m "my message"` when you're pushing to GitHub

**Comment by albanD** [comment]
I think a default that increments: [Update 1] ..., [Update 2] ..., etc would help.
I think what confuses a lot of users is github history like this:
![image](https://github.com/ezyang/ghstack/assets/6359743/ba3a48ec-d1bd-4146-a64e-f2020c8e74cc)

If the names were not the exact same every time that would make this a lot easier to parse.
