### ISSUE TITLE
Automatically delete head branches option makes ghstack land fail

### ISSUE THREAD

**Issue by xiphirx** [ezyang/ghstack#63]
When you have the `Automatically delete head branches` option enabled for PR merges, ghstack errors out when landing due to the head branch already being deleted: 

```
error: failed to push some refs to 'git@github.com:foo/foo.git'
$ git checkout main
Previous HEAD position was a12eb99 foo commit message
Switched to branch 'main' 
ERROR: Fatal exception
Traceback (most recent call last): 
File "/home/xiphirx/.local/lib/python3.8/site-packages/ghstack/logs.py", line 107, in manager
yield
File "/home/xiphirx/.local/lib/python3.8/site-packages/ghstack/__main__.py", line 123, in main
ghstack.land.main(
File "/home/xiphirx/.local/lib/python3.8/site-packages/ghstack/land.py", line 130, in main
sh.git("push", remote_name, "--delete", orig_ref, base_ref, head_ref)
File "/home/xiphirx/.local/lib/python3.8/site-packages/ghstack/shell.py", line 271, in git
return self._maybe_rstrip(self.sh(*(("git",) + args), **kwargs))
File "/home/xiphirx/.local/lib/python3.8/site-packages/ghstack/shell.py", line 210, in sh
raise RuntimeError(
RuntimeError: git push origin --delete gh/xiphirx/2/orig gh/xiphirx/2/base gh/xiphirx/2/head failed with exit code 1
```

Turning the option off makes ghstack work as expected, but I think it would be cool if ghstack would recognize that the branch is already gone + skip deleting it + delete the others and continue on like normal.

**Comment by xiphirx** [comment]
It seems like you could potentially use `git ls-remote --head origin <branch name>` to check for the existence before issuing the delete command. Im not sure if its possible to tell git to "keep going" if it encounters a non-existent branch, but that would be preferable imo.

**Comment by ezyang** [comment]
Sounds reasonable. Another quick and dirty fix would just be to suppress all errors from the delete branch command.

**Comment by xiphirx** [comment]
If we suppress errors it still means we have lingering branches (if one branch doesnt exist, none of them get deleted it seems), unless you have a way in git to suppress the  error but continue with the deletions?

**Comment by ezyang** [comment]
I wasn't too familiar with Git's semantics here. But we could always issue the deletions individually and/or decide we don't care (it's not the end of the world if we fail to delete the branch)
