### ISSUE TITLE
ghstack produced weird PR description when the top PR in the stack starts with a bulleted list

### ISSUE THREAD

**Issue by garymm** [ezyang/ghstack#74]
It's really confusing here that the bulleted list transitions from a list of PRs in the stack to the list that was in the original PR description:
https://github.com/pytorch/pytorch/pull/60249

Some formatting that makes it clear where the original PR description begins would be helpful in this csae.

**Comment by ezyang** [comment]
Yeah ok, some logic to detect a leading bullet list and insert a divider seems reasonable
