### ISSUE TITLE
GPG signed commits

### ISSUE THREAD

**Issue by robin5540** [ezyang/ghstack#77]
Not sure if these is a local config I can enable for this. I can't find any thing that enables signing on `commit-tree` automatically.

If there isn't a git config, I see two ways of adding this feature:
1. add a config line for commit signing and optionally allow keyid to be passed in from that config line. i.e.
```
None   => don't sign
""     => sign with default key
keyid  => sign with key id
```
2. check `git config --list` and use the key and behavior in there.

**Comment by ezyang** [comment]
I would accept a patch that emulate's git's porcelain behavior w.r.t commit.gpgsign
