### ISSUE TITLE
merge commits using the normal GitHub UI or provide a CLI

### ISSUE THREAD

**Issue by edward-io** [ezyang/ghstack#9]
From the README:

> You will NOT be able to merge these commits using the normal GitHub UI, as their branch bases won't be master. For the PyTorch repository, we have a special mechanism for landing diffs; if you need a way to land these commits on a regular GitHub repository, give a holler on issues and we'll add this functionality.

Stacking diffs in Phabricator is awesome, would be great to have this feature in open source repos as well.

**Comment by ezyang** [comment]
Hey @edward-io, you're our first external user :) Would you be interested in taking stewardship over this feature? There's some (non-working) code in ghstack/land.py that gives the general flavor of how landing ought to work and I can give advice about how to implement it.

**Comment by ezyang** [comment]
ghstack land works now on master. Give it a try.

**Comment by AnthonyMillerSF** [comment]
That's super exciting! Can you update your README, because it still says there is no real way to land this on master.
