### ISSUE TITLE
make it possible/easy to recover ghstack metadata when the original local branch is deleted

### ISSUE THREAD

**Issue by nkaretnikov** [ezyang/ghstack#91]
so, i haven't looked much into this, just noticed that ghstack strips the metadata after pushing to remote (still available locally tho). now, what would happen if a user accidentally deletes their branch/checkout but still wants to push more commits as part of the original stack?

i know that ghstack uses the tree hash, but i haven't checked how difficult (or possible at all) it would be to recover in a situation like this.

thoughts?

ps: why is metadata stripped in the first place? is it to protect others from messing with your stack?

**Comment by ezyang** [comment]
`ghstack checkout PR_URL` lets you retrieve the original (with metadata) commit for adding more commits on the stack. Internally, this is stored in the "orig" branch which is not visible from the PR but is always pushed alongside head and base
